### ISSUE TITLE
Please don't give up on assembly!

### ISSUE THREAD

**Issue by stacksmith** [CorruptedByCPU/Cyjon#129]
I am sure you have many valid reasons to use C, but may I suggest that you stay in asm?

So many low-level concepts are more succinctly expressed in assembly!  Just look at the layers and layers of C headers required to wrap around the hardware registers alone - something which is a given in assembly.  

If that does not convince you, consider that right now this is a unique and valuable project.  Convert it to C and with will be just another half-baked hobby OS!

Either way, thank you for your work!

**Comment by CorruptedByCPU** [comment]
Hey!

`but may I suggest that you stay in asm?`
I still operate in assembler, I'm constantly parsing C code in debuggers.

`low-level concepts are more succinctly expressed in assembly! Just look at the layers and layers of C headers`
That's true, but my code written in C is just as simple as if I were writing in assembly language.

`consider that right now this is a unique and valuable project`
That might be true :)

### I learned a lot of things while spending time in C and I will not fail to implement them in Cyjon. But as is usually it is the case - too little time, too much to do.
