### ISSUE TITLE
binary memory map

### ISSUE THREAD

**Issue by CorruptedByCPU** [CorruptedByCPU/Cyjon#15]
the binary memory map describes only one space, starting with the physical address 0x00100000
process the rest of the memory map entries and describe them in a binary memory map

**Comment by EmadDeve20** [comment]
Hi, @Blackend  Your project is very good and I like it. I think your project needs to be completed with C or Rust language ...
No?
So I can help you but I need a Long time to read your source and learning assembly.
May I ask you why you created this project? Or what was your motivation?

**Comment by Blackend** [comment]
There really is no need for help ;) Besides, I keep all the comments in my own language - and I have no spare strength to rewrite, so it is a significant obstacle.

**Comment by EmadDeve20** [comment]
Hello. and you are not thinking of ambition? If I could add a Rust language to it, it would be really great, even from Linux. The assembly language is not very efficient and you can learn Rust soon if you want. Of course, it depends on the purpose and interest.

**Comment by EmadDeve20** [comment]
Hello. and you are not thinking of ambition? If I could add a Rust language to it, it would be really great, even from Linux. The assembly language is not very efficient and you can learn Rust soon if you want. Of course, it depends on the purpose and interest.

**Comment by EmadDeve20** [comment]
Ok, bro.
If you need help, I'm here : D
